<center><img src="/work/img/numpy_logo.png"></center>

<h1>NumPy (Numerical Python)</h1>
<p><em><b>Manual de Referencia NumPy:</b> <a href="https://numpy.org/doc/stable/numpy-ref.pdf">https://numpy.org/doc/stable/numpy-ref.pdf</a></em></p>
<p>Es una librería de Python que provee una serie de métodos para realizar operaciones matemáticas sobre una estructura de datos en forma de matriz (llamado <b>array</b>), que puede ser uni-dimensional (arreglo), bi-dimensional (matriz) o n-dimensional (tensores).</p>
<center><img src="/work/img/numpy1.png"></center>
<p>Un array NumPy es un paquete de matrices N-dimensional que tienen forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria.</p>


<h3>Instalación</h3>
<p>Al trabajar en un entorno local, debemos instalar el paquete NumPy. <b>Recordá crear un entorno virtual previamente.</b> Si estamos trabajando en entornos tipo notebook, no necesitamos instalar ningún paquete para trabajo con datos (NumPy, PanDas, Matplotlib, etc.), sólo necesitamos importarlos.</p>
<center><img src="/work/img/instala_numpy.png"></center>

<h3>Importando la librería</h3>
<center><img src="/work/img/importar_numpy.png"></center>

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np
from scipy import stats # para la moda

#USOS BÁSICOS
lista_nros = [12,12,14,15,16,16,16,20,2,3,4,5,5,7,8,10,22,22]

'''
Para poder manipular mi lista python con numpy, necesito convertirla en un ARREGLO o 
VECTOR
Voy a usar el método array() de numpy y le voy a pasar como parámetro la lista
Como le puse un alias a mi numpy importado (np), lo voy a usar para invocar a 
este método de ahora en adelante
'''

array_nros = np.array(lista_nros)
#array_nros = np.array([12,12,14,15,16,16,16,20,2,3,4,5,5,7,8,10,22,22])
print(array_nros) # misma distribución que la lista, pero es matriz
print(lista_nros)
print(type(array_nros))


[12 12 14 15 16 16 16 20  2  3  4  5  5  7  8 10 22 22]
[12, 12, 14, 15, 16, 16, 16, 20, 2, 3, 4, 5, 5, 7, 8, 10, 22, 22]
<class 'numpy.ndarray'>


<h3>Medidas de tendencia central en NumPy</h3>

In [3]:
# MEDIA -> método mean()
array_nros = np.array([5,5,5,7,8,10,12,12,14,15,16,16,16,20,2,2,2,3,4,22,22])
media = np.mean(array_nros)
print(f"Promedio/Media: {media}") # numpy nos da hasta 16 decimales si no se especifica otra cosa
print(f"Promedio/Media: {media:.2f}") # damos formato de 2 decimales con :.2f


Promedio/Media: 10.380952380952381
Promedio/Media: 10.38


In [4]:
# MEDIANA --> método median()
mediana = np.median(array_nros)
print(f"Mediana: {mediana}")

Mediana: 10.0


In [5]:
# CUARTILES --> numpy.quantile(datos, q)
q1 = np.quantile(array_nros, 0.25)
q2 = mediana
q3 = np.quantile(array_nros, 0.75)

print(f"Q1 = {q1} - Q2 = {q2} - Q3 = {q3}")


Q1 = 5.0 - Q2 = 10.0 - Q3 = 16.0


In [6]:
# PERCENTIL -> Es una medida de dispersión parecida a los cuartiles pero que divide 
# la muestra en 100 => trabaja con porcentajes
# método percentile(arreglo, cuántos elementos tomar)
p60 = np.percentile(array_nros, 60)
p20 = np.percentile(array_nros, 20)
p50 = np.percentile(array_nros, 50)

print("Percentil 60:", p60) # el 60% de los datos ---> menor que q3, que es el 75%
print("Percentil 20:", p20) # el 20% de los datos ---> menor que q1, que es el 25%
print("Percentil 50:", p50) # el 50% de los datos ---> coincide ocnla mediana



Percentil 60: 12.0
Percentil 20: 4.0
Percentil 50: 10.0


In [7]:
''' MODA
me devuelve un objeto de tipo ModeResult(array_con_el_primer_valor_que_encuentra, 
recuento_de_apariciones)
Sólo devuelve la primera ocurrencia en un vector ORDENADO si hay más valores, 
los ignora '''
# son todos módulos de numpy, excepto mode() que es de scipy

moda = stats.mode(array_nros)
print("Moda:", moda)


Moda: ModeResult(mode=array([2]), count=array([3]))
/tmp/ipykernel_198/2644800578.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  moda = stats.mode(array_nros)


In [8]:
# Varianza --> método var()
varianza = np.var(array_nros)
print(f"Varianza: {varianza}")
print(f"Varianza: {varianza:.2f}")


Varianza: 43.188208616780045
Varianza: 43.19


In [9]:
# Desvío Standard --> raíz cuadrada de la varianza
desvio_std = np.std(array_nros)
print(f"Desvío stardard: {desvio_std:.2f}")
print(desvio_std**2)

Desvío stardard: 6.57
43.188208616780045


<h3>Creando estructuras de datos con NumPy</h3>

Los arreglos en Numpy tienen que tener <b>sí o sí</b> los mismos tipos de datos -> los diferencia de las listas Py.

A los elementos de un vector se accede como a lo de los iterables conocidos -> con índice.

Les puedo aplicar slicing.

In [10]:
# CREAR ARREGLOS = ARRAY = VECTOR -> 1 fila, n columnas
# MATRIZ UNIDIMENSIONAL
arr = np.array([99,5,5,5,7,8,10,12,33,56,123,234,12,14,15,16,16,16,20,2,2,2,3,4,22,22,1000])
print('Primer elemento:', arr[0] )
print('Último elemento:', arr[-1])


Primer elemento: 99
Último elemento: 1000


In [11]:
# CREAMOS UNA MATRIZ = ARREGLO BI-DIMENSIONAL
dosd = [[1,10,2],[9,3,5]]
print(f'Lista\n {dosd}')
print()

dosda = np.array(dosd)
print(f'Arreglo numpy\n {dosda}' )
print()

# ACCEDIENDO A LOS VALORES DE LA MATRIZ --> coordenadas[fila, columna]
print(dosda[0,1])


Lista
 [[1, 10, 2], [9, 3, 5]]

Arreglo numpy
 [[ 1 10  2]
 [ 9  3  5]]

10


In [54]:
# En un array los datos deben ser homogéneos
lv = [1, 'hora', 0.5, True]
array_lv = np.array(lv)
print(array_lv)

['1' 'hora' '0.5' 'True']


<h4>ACTIVIDAD</h4>
<ul><li>Crear dos listas con datos de tipo homogéneo.</li>
<li>Una de las listas -> convertirla a vector</li>
<li>La otra -> convertirla a una matriz de 3 filas x 4 columnas</li></ul>

In [60]:
# Ejecicico resuelto

import numpy as np

#Crear dos listas de datos de tipo homogéneo.
tickers1 = ['MSFT', 'AAPL', 'FB', 'AMZN']
tickers2 = ['BMA', 'BYMA', 'CEPU', 'COME', 'MSFT', 'AAPL', 'FB', 'GOOGL', 'TSLA', 'NVDA', 'NFLX', 'AMZN']

# Convertir a un vector (array unidimensional)
vector = np.array(tickers1)
print("Vector:", tickers1)

# Convertir a una matriz de 3 filas x 4 columnas
matriz = np.array(tickers2).reshape(3, 4)
print("Matriz 3x4:\n", matriz)


Vector: ['MSFT', 'AAPL', 'FB', 'AMZN']
Matriz 3x4:
 [['BMA' 'BYMA' 'CEPU' 'COME']
 ['MSFT' 'AAPL' 'FB' 'GOOGL']
 ['TSLA' 'NVDA' 'NFLX' 'AMZN']]


<h3>Forzando el tipo de dato</h3>

In [13]:
array1 = np.array([[1.5,2,3,4],[5,6,7,8]]) # dtype
array2 = np.array([[1.5,2,3,4],[5,6,7,8]], dtype=np.int64) 

print(array1)
print()
print(array2)

[[1.5 2.  3.  4. ]
 [5.  6.  7.  8. ]]

[[1 2 3 4]
 [5 6 7 8]]


<h3>Arreglos vacíos</h3>
<p>A veces se crean arreglos vacíos, para luego ser rellenados.</p>
<p>Se inicializan con unos, ceros, valores espaciados uniformemente, valores constantes o valores aleatorios. </p>

In [14]:
# arreglo de unos --> float
unos = np.ones(3)
unos2 = np.ones((4,5)) # doble paréntesis
unos3 = np.ones((4,5), dtype=np.int64) # enteros

print(unos)
print()
print(unos2)
print()
print(unos3)

[1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
# arreglo de ceros 
unos = np.zeros(3)
unos2 = np.zeros((4,5)) # doble paréntesis
unos3 = np.zeros((4,5), dtype=np.int64) # enteros

print(unos)
print()
print(unos2)
print()
print(unos3)

[0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
# arreglo de nros aleatorios  --> método random
# SUBMÉTODO random() --> nro aleatorio entre 0 y 1
a1 = np.random.random(3)
print(a1)
print()
a2 = np.random.random((3,5))
print(a2)
print()
# SUBMÉTODO randint()
a3 = np.random.randint(1,6,5) # random.randint(mínimo, máximo(-1), cantidad)
print(a3)
print()
a4 = np.random.randint(1,6,(4,5))
print(a4)

[0.36102493 0.55748367 0.25634449]

[[0.48871164 0.09231881 0.58944331 0.08775317 0.06351907]
 [0.51460726 0.21007191 0.69371823 0.04216091 0.32996194]
 [0.02684302 0.43332628 0.84998562 0.20820773 0.01782993]]

[2 2 5 2 4]

[[2 5 4 2 1]
 [2 1 1 1 4]
 [1 3 5 5 1]
 [1 1 2 4 3]]


In [17]:
# llena todo el arreglo con el mismo valor
ochos = np.full((4,5), 8)
print(ochos)
print()
mochos = np.full((4,5), 'hola')
print(mochos)
print()
tochos = np.full((4,5), True)
print(tochos)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]

[['hola' 'hola' 'hola' 'hola' 'hola']
 ['hola' 'hola' 'hola' 'hola' 'hola']
 ['hola' 'hola' 'hola' 'hola' 'hola']
 ['hola' 'hola' 'hola' 'hola' 'hola']]

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


Para crear arreglos con valores espaciados uniformemente podemos utilizar np.arange() y np.linspace()


In [18]:
# np.arange(): deseo crear un arreglo con los valores comprendidos entre 0 y 100 a paso 5
esp1 = np.arange(0,101,5)
print(esp1)
print()
# np.linspace(): deseo crear 5 valores que se encuentren entre 0 y 2
# esp2 = np.arange(0,2.1,0.5) 
esp2 = np.linspace(0,2,5) # linspace(inicio, tope(entra), cantidad)
print(esp2)
# np.linspace(min, max, n) me divide el rango en min-max en n partes y llena el arreglo con los valores que me da la división
 

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]

[0.  0.5 1.  1.5 2. ]


<h3>Matriz identidad</h3>

In [19]:
mi = np.eye(4)
print(mi)
print()
mi2 = np.eye(4, dtype=np.int64)
print(mi2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


<h3>Inspeccionar arreglos</h3>


In [20]:
arreglo = np.array([(1, 3, 5, 7), (9.5, 3, 4, 5), (1, 1, 1, 1)])
print(arreglo.shape) # tupla de filas, columnas
print(arreglo.dtype) # tipo de dato
print(arreglo.size)


(3, 4)
float64
12


<h3>Cambio de tamaño y forma</h3>

In [21]:
# Sólo puedo darle la forma que se ajuste a la cantidad de elementos que me tira el atributo size
m1 = np.array([(8,9,10),(11,12,13)])
print(m1)
print()
m2 = m1.reshape(3,2)
print(m2)
print()
m3 = m1.reshape(1,6)
print(m3)
print()
m4 = m1.reshape(6,1)
print(m4)
print()


[[ 8  9 10]
 [11 12 13]]

[[ 8  9]
 [10 11]
 [12 13]]

[[ 8  9 10 11 12 13]]

[[ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]



<h3>Operaciones matemáticas</h3>

In [22]:
a = np.arange(4)
print(a)
b = a*.21
print(b)
c = a+b
print(c)
# aplica para las operaciones -, /,//, **, %

[0 1 2 3]
[0.   0.21 0.42 0.63]
[0.   1.21 2.42 3.63]


<h3>Universal functions (ufunc)</h3>
https://www.w3schools.com/python/numpy/numpy_ufunc.asp También ejecutan una operación elemento a elemento sobre un arreglo Reemplazan los operadores individuales. Son funciones nativas

Ejemplos:
<ul><li>np.add(vector,4) # suma 4</li>
<li>np.substract(vector,2) # resta 2</li>
<li>np.multiply</li>
<li>np.floor_divide(vector,3) # devuelve la division entera</li>
<li>np.negative(vector)</li>
<li>np.power(vector,2) #potencia</li>
<li>np.mod(vector,2)</li></ul>

In [23]:
vector = np.array([(8, 9, 10), (11, 12, 13)])
print(vector.min())
print(vector.max())
print(vector.sum())
print(np.sqrt(vector)) # raíz cuadrada
print(np.std(vector)) # desvío std
print(np.negative(vector)) # negativos
print(np.power(vector, 3)) # función **
print(np.mod(vector,2)) # función %

8
13
63
[[2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128]]
1.707825127659933
[[ -8  -9 -10]
 [-11 -12 -13]]
[[ 512  729 1000]
 [1331 1728 2197]]
[[0 1 0]
 [1 0 1]]


In [24]:
#from scipy import stats
#SciPy es un biblioteca de algoritmos matemáticos


<h3>Método append</h3>
Para agregar filas o columnas

In [25]:
mi_array = np.array(([1,4,19,10,5],[3,9,10,8,8]))
e = ([0,0,0,0,0],[1,1,1,1,1])



In [26]:
# MÉTODO APPEND: ARRAY ORIGINAL +  2 FILAS EXTRA
# axis=0 agrega filas
print(mi_array)
print()
arr2 = np.append(mi_array, e, axis = 0)
print(arr2)

[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]

[[ 1  4 19 10  5]
 [ 3  9 10  8  8]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]]


In [27]:
# MÉTODO APPEND: ARRAY ORIGINAL + 5 COLUMNAS EXTRA
arr3 = np.append(mi_array, e, axis = 1)
print(arr3)


[[ 1  4 19 10  5  0  0  0  0  0]
 [ 3  9 10  8  8  1  1  1  1  1]]


<h3>Repaso de acceso a los elementos y slicing</h3>
Para obtener fragmentos de nuestros sets de datos.

In [28]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
print(a)


[[ 1  0  3]
 [ 4  3  5]
 [ 6 10 -1]]


In [29]:
# Quiero acceder al 10 (recuerdo que las posiciones empiezan a contarse desde 0)
print(a[2,1])
print()
print(a[1:,1:])


10

[[ 3  5]
 [10 -1]]


In [30]:
# recordemos que si estamos en un array de una sola dimensión, ponemos únicamente 
# el índice que corresponde al elemento que buscamos y listo!
a2 = np.array([25, 36, 10, 85, 56])
print(a2[2])


10


In [31]:
# SLICING TOTAL -> Para obtener todos los elementos
a2 = np.array([25, 36, 10, 85, 56])
print(a2[:])
print(a2[::2])


[25 36 10 85 56]
[25 10 56]


Puedo usar RANGOS de búsqueda, usando el mismo formato <code><mark>inicio:tope:paso</mark></code> de range.
Supongamos que quiero obtener los datos de las celdas:
<ul><li>naranja</li>
<li>turquesa</li>
<li>rojo</li>
<li>verde</li></ul>
<center><img src='/work/img/slicing.png'></center>

In [32]:
# CREO LA MATRIZ
matriz = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
print(matriz)


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [33]:
# BUSCO EL RANGO EN NARANJA
print(matriz[0,3:5])


[3 4]


In [34]:
# BUSCO EL RANGO TURQUESA
print(matriz[4:,4:])


[[44 45]
 [54 55]]


In [35]:
# BUSCO EL RANGO ROJO
print(matriz[:,2])


[ 2 12 22 32 42 52]


In [36]:
# Si quiero que se imprima en columna, recuerdo que tengo el método reshape(filas,columnas)
print(matriz[:,2].reshape(6,1))

[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]


In [37]:
# BUSCO EL RANGO VERDE
print(matriz[2::2,::2])


[[20 22 24]
 [40 42 44]]


<h3>Boolean Masking</h3>
Puedo obtener información sobre el contenido de mi arreglo, como valores repetidos, por encima o debajo de cierto valor, etc.

Podemos hacerlo mediante operadores mediante o ufuncs

In [38]:
# CREO UNA MATRIZ CON VALORES ALEATORIOS, pero no quiero que cambien los valores cada vez que ejecuto mi código
np.random.seed(0) 
a = np.random.randint(0,100,(20,20))
print(a)


[[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
 [81 37 25 77 72  9 20 80 69 79 47 64 82 99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31 74 23 35 75 55 28 34  0  0 36 53  5 38]
 [17 79  4 42 58 31  1 65 41 57 35 11 46 82 91  0 14 99 53 12]
 [42 84 75 68  6 68 47  3 76 52 78 15 20 99 58 23 79 13 85 48]
 [49 69 41 35 64 95 69 94  0 50 36 34 48 93  3 98 42 77 21 73]
 [ 0 10 43 58 23 59  2 98 62 35 94 67 82 46 99 20 81 50 27 14]
 [41 58 65 36 10 86 43 11  2 51 80 32 54  0 38 19 46 42 56 60]
 [77 30 24  2  3 94 98 13 40 72 19 95 72 26 66 52 67 61 14 96]
 [ 4 67 11 86 77 75 56 16 24 29 21 25 80 60 61 83 33 32 70 85]
 [31 13 71 56 24 79 41 18 40 54 79 11 38 93  1 95 44 88 24 67]
 [82  3 76 35 86 61 69 87 43 32 11 84 10 54 37 28  2 27 83 89]
 [23 53 51 46 20 53 29 67 35 39  9 73 41 23  3 46 90 50  3 31]
 [ 9 10 27 45 71 39 61 85 97 44 34 34 88 33  5 36  0 75 34 69]
 [53 80 62  8 61  1 81 35 91 40 36 48 25 67 35 30 29 33 18 17]
 [93 84  2 69 12 44 66 91 85 39 39 75 22 30 17 70 71 18

In [39]:
# Uso operadores para buscar valorese < 50
print(a < 50)



[[ True  True False False False  True False  True  True False False False
  False  True False False  True False  True False]
 [False  True  True False False  True  True False False False  True False
  False False False  True  True  True  True  True]
 [ True  True False  True False  True  True False  True  True False False
   True  True  True  True  True False  True  True]
 [ True False  True  True False  True  True False  True False  True  True
   True False False  True  True False False  True]
 [ True False False False  True False  True  True False False False  True
   True False False  True False  True False  True]
 [ True False  True  True False False False False  True False  True  True
   True False  True False  True False  True False]
 [ True  True  True False  True False  True False False  True False False
  False  True False  True False False  True  True]
 [ True False False  True  True False  True  True  True False False  True
  False  True  True  True  True  True False False]


In [40]:
# valores = 44
print(a == 44)

[[ True False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]


In [41]:
# Con Ufuncs busco elementos = 30
print(np.equal(a, 30))


[[False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]


In [42]:
# menores a 32
print(np.less(a,32))



[[False False False False False  True False  True False False False False
  False  True False False False False False False]
 [False False  True False False  True  True False False False False False
  False False False False  True  True  True  True]
 [False False False  True False False  True False  True False False False
   True False  True  True False False  True False]
 [ True False  True False False  True  True False False False False  True
  False False False  True  True False False  True]
 [False False False False  True False False  True False False False  True
   True False False  True False  True False False]
 [False False False False False False False False  True False False False
  False False  True False False False  True False]
 [ True  True False False  True False  True False False False False False
  False False False  True False False  True  True]
 [False False False False  True False False  True  True False False False
  False  True False  True False False False False]


In [43]:
# Contando valores especificos en toda la matriz
# valores != 0
print(np.count_nonzero(a))

# Contando valores específicos por fila, agregando la opción axis
print(np.sum(a < 50, axis = 1))

391
[ 8 10 14 12  9 10 10 12  9  9 11 10 13 13 13 10  8  5 12 10]


<h3>Método copy</h3>
Permite crear copias de arrays.

In [44]:
a4 = np.array(([1,4,19,10,5],[3,9,10,8,8]))
a5 = a4 ### OJOOOOOO así no se copian los arrays
print(a4)
print()
print(a5)
a5[0,0] = 1000 
print()
print(a4)
print()
print(id(a4))
print(id(a5))

[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]

[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]

[[1000    4   19   10    5]
 [   3    9   10    8    8]]

140074968516528
140074968516528


In [45]:
a6 = np.copy(a4)  # METODO PARA COPIAR ARRAYS
a6[0,0] = 5 
print(a4)
print()
print(a6)
print()
print(id(a4))
print(id(a6))

[[1000    4   19   10    5]
 [   3    9   10    8    8]]

[[ 5  4 19 10  5]
 [ 3  9 10  8  8]]

140074968516528
140074968516912


<h3>Arreglos de Booleanos</h3>
Con dtype puedo cambiar cómo se muestran los valores en pantalla

In [46]:
b1 = np.array([1,0,1,1,0,1,0,0])
b2 = np.array([1,0,1,1,0,1,0,0], dtype=bool)

print(b1)
print(b2)

# Recordemos que cualquier nro!=0 es un True


[1 0 1 1 0 1 0 0]
[ True False  True  True False  True False False]


In [47]:
b1 = np.array([1,0,1,1,0,1,0,0])
b3 = np.array([0,0,1,0,1,1,0,1])

# Operamos
b4 = b1 & b3
b5 = b1 | b3

print(b4)
print(b5)


[0 0 1 0 0 1 0 0]
[1 0 1 1 1 1 0 1]


In [48]:
# Aplicando ufuncs obtengo los valores True y False
b6 = np.logical_and(b1, b3)
b7 = np.logical_or(b1, b3)

print(b6)
print(b7)


[False False  True False False  True False False]
[ True False  True  True  True  True False  True]


<h3>all() y any()</h3>
Métodos para evaluar todos los valores de un arreglo

In [49]:
b1 = np.array([1,0,1,1,0,1,0,0])
b8 = np.array([0,0,0,0,0,0,0,0])
b9 = np.array([1,1,1,1,1,1,1,1])

# Todos los valores son True?
print(np.all(b1))
print(np.all(b8))
print(np.all(b9))
print()

# Alguno de los elementos del arreglo es True?
print(np.any(b1))
print(np.any(b8))
print(np.any(b9))

False
False
True

True
False
True


<h3>Broadcasting</h3>
NumPy me permite operar entre arreglos de diferente estructura, transformándolos para que tengan el mismo tamaño para que no se generen errores.

Así es el proceso:
<center><img src='/work/img/broadcasting.png'></center>

In [50]:
v1 = np.arange(0,40,10)
print(v1)
print(v1.shape)

[ 0 10 20 30]
(4,)


In [51]:
v2 = v1[:,np.newaxis] # crea copia y cambia orientación
print(id(v1))
print(id(v2))
print()
print(v2)

140074968547952
140074968547568

[[ 0]
 [10]
 [20]
 [30]]


In [52]:
print(v1)
print()
print(v2)
print()
print(v1 + v2)

[ 0 10 20 30]

[[ 0]
 [10]
 [20]
 [30]]

[[ 0 10 20 30]
 [10 20 30 40]
 [20 30 40 50]
 [30 40 50 60]]


<h4>Actividades</h4>
1. Crear un vector3 de 1 fila y 6 columnas con los datos 5,10,15,20,25,30
   Crear un vector4 de 5 filas y 1 columna con los datos 100,200,300,400,500
   (Crédito extra para quien use arange + newaxis para crear los vectores)
   Crear el vector5, a partir de vector4 - vector3

2. Usando slicing, obtener de vector5 los siguientes datos y cargarlos en vector6,vector7,vector8:

In [53]:
'''
a. [[ 285 280 275 ]
    [ 385 380 375 ]]

b. [ 290 280 270 ]

c. [[  75 ]
    [ 275 ]
    [ 475 ]]
'''

'\na. [[ 285 280 275 ]\n    [ 385 380 375 ]]\n\nb. [ 290 280 270 ]\n\nc. [[  75 ]\n    [ 275 ]\n    [ 475 ]]\n'

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=657ca745-6eb9-4c68-96b5-44f61400fd46' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>