# Numpy Ejercicios

## Ejercicio 1

Crear un vector con valores dentro del rango 10 a 49.

## Ejercicio 2

Invertir el vector.

## Ejercicio 3

Crear una matriz 3x3 con valores de 0 a 8.

## Ejercicio 4

Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

## Ejercicio 5

Crear una matriz identidad de 6x6.

## Ejercicio 6

Crear una matriz con valores al azar con forma 3x3x3.

## Ejercicio 7

Encontrar los indices de los valores minimos y maximos de la anterior matriz

## Ejercicio 8

Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

## Ejercicio 9

Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

## Ejercicio 10

Crear dos arreglos al azar A y B, verificar si son iguales

In [1]:
import numpy as np

# Ejercicio 1: Crear un vector con valores dentro del rango 10 a 49
vector = np.arange(10, 50)
print("Ejercicio 1:", vector)

# Ejercicio 2: Invertir el vector
vector_invertido = vector[::-1]
print("Ejercicio 2:", vector_invertido)

# Ejercicio 3: Crear una matriz 3x3 con valores de 0 a 8
matriz_3x3 = np.arange(9).reshape(3, 3)
print("Ejercicio 3:\n", matriz_3x3)

# Ejercicio 4: Encontrar los indices que no son ceros del arreglo
arreglo = np.array([1, 2, 4, 2, 4, 0, 1, 0, 0, 0, 12, 4, 5, 6, 7, 0])
arreglo_sin_ceros = np.nonzero(arreglo)
print("Ejercicio 4:", arreglo_sin_ceros)

# Ejercicio 5: Crear una matriz identidad de 6x6
matriz_identidad = np.eye(6)
print("Ejercicio 5:\n", matriz_identidad)

# Ejercicio 6: Crear una matriz con valores al azar con forma 3x3x3
matriz_azar = np.random.random((3, 3, 3))
print("Ejercicio 6:\n", matriz_azar)

# Ejercicio 7: Encontrar los indices de los valores minimos y maximos de la matriz anterior
indice_min = np.unravel_index(np.argmin(matriz_azar), matriz_azar.shape)
indice_max = np.unravel_index(np.argmax(matriz_azar), matriz_azar.shape)
print("Ejercicio 7: Mínimo en", indice_min, ", Máximo en", indice_max)

# Ejercicio 8: Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior
matriz_10x10 = np.ones((10, 10))
matriz_10x10[1:-1, 1:-1] = 0
print("Ejercicio 8:\n", matriz_10x10)

# Ejercicio 9: Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4
matriz_5x5 = np.tile(np.arange(5), (5, 1))
print("Ejercicio 9:\n", matriz_5x5)

# Ejercicio 10: Crear dos arreglos al azar A y B, verificar si son iguales
A = np.random.random(10)
B = np.random.random(10)
iguales = np.array_equal(A, B)
print("Ejercicio 10: ¿Son iguales A y B?", iguales)


Ejercicio 1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Ejercicio 2: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Ejercicio 3:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Ejercicio 4: (array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14]),)
Ejercicio 5:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Ejercicio 6:
 [[[0.35750826 0.07321195 0.69181945]
  [0.65569104 0.69182619 0.32366811]
  [0.08194118 0.78605807 0.63590911]]

 [[0.45845757 0.67789931 0.17175672]
  [0.40120998 0.58058155 0.51421484]
  [0.03278976 0.83529364 0.92149425]]

 [[0.54216675 0.96232324 0.75822445]
  [0.81138319 0.25219365 0.66668875]
  [0.97232391 0.71830248 0.55807167]]]
Ejercicio 7: Mínimo en (1, 2, 0) , Máximo en (2, 2, 0)
Ejercicio 8:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=657ca745-6eb9-4c68-96b5-44f61400fd46' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>